name: Release

on:
  workflow_dispatch:
  # or schedule / push triggers, as you prefer
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  release:
    # Make sure the BOT can push tags to main
    # (and commits if that is required by your semantic-release config)
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out with BOT credentials
        uses: actions/checkout@v4
        with:
          # Use your BOT token so you can push to main
          token: ${{ secrets.BOT_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.13'

      - name: Install
        run: npm ci

      - name: Run semantic-release
        env:
          # Provide the BOT token to semantic-release
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          # If you need NPM_TOKEN or anything else, specify here
        run: npx semantic-release
