name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is fetched for semantic-release

      # 2. Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'  # Uses the latest LTS version of Node.js
          cache: 'npm'           # Caches npm dependencies to speed up builds

      # 3. Install project dependencies
      - name: Install dependencies
        run: npm ci

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Allows writing to repository contents (e.g., creating releases)
      packages: write    # Allows publishing to GitHub Packages
    steps:
      # 1. Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is fetched for semantic-release

      # 2. Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'  # Uses the latest LTS version of Node.js
          cache: 'npm'           # Caches npm dependencies to speed up builds

      # 3. Install project dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Release the project using semantic-release
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Provided by GitHub Actions for authentication
        run: npx semantic-release
