name: Release

on:
  workflow_dispatch:
  # or schedule / push triggers, as you prefer
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  release:
    # Make sure the BOT can push tags to main
    # (and commits if that is required by your semantic-release config)
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out with BOT credentials
        uses: actions/checkout@v4
        with:
          # Use your BOT token so you can push to main
          token: ${{ secrets.BOT_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.13'

      - name: Install
        run: npm ci

      - name: Create a new branch
        run: |
          git config --global user.email "eugenioandruccioli@gmail.com"
          git config --global user.name "CryptoMonitor-CI"
          git checkout -b test-branch-${{ github.run_id }}
          echo "Dummy change" >> dummy.txt
          git add dummy.txt
          HUSKY=0 git commit -m "Test commit for branch test-branch-${{ github.run_id }}"
          git push origin test-branch-${{ github.run_id }}
        env:
          # Use BOT token for authentication
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}


