name: Generate Dokka Docs and Commit to Docs Folder

on:
  push:
    branches:
      - develop

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate Dokka HTML Documentation
        run: ./gradlew dokkaHtml

      - name: Move Documentation to Docs Folder
        run: |
          mkdir -p docs
          rm -rf docs/*  # Clean previous docs
          cp -r app/build/dokka/html/* docs/

      - name: Commit and Push Documentation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git diff --cached --quiet || git commit -m "Update Dokka documentation"
          git push https://x-access-token:${{ secrets.BOT_TOKEN }}@github.com/${{ github.repository }}.git

